# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_pic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 360)
        self.label_light = QtWidgets.QLabel(Form)
        self.label_light.setGeometry(QtCore.QRect(40, 40, 150, 220))
        self.label_light.setObjectName("label_light")
        self.label_fan = QtWidgets.QLabel(Form)
        self.label_fan.setGeometry(QtCore.QRect(220, 40, 150, 220))
        self.label_fan.setObjectName("label_fan")
        self.btn_light = QtWidgets.QPushButton(Form)
        self.btn_light.setGeometry(QtCore.QRect(50, 290, 93, 28))
        self.btn_light.setObjectName("btn_light")
        self.btn_fan = QtWidgets.QPushButton(Form)
        self.btn_fan.setGeometry(QtCore.QRect(240, 290, 93, 28))
        self.btn_fan.setObjectName("btn_fan")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图片显示"))
        self.label_light.setText(_translate("Form", "light"))
        self.label_fan.setText(_translate("Form", "fan"))
        self.btn_light.setText(_translate("Form", "开灯"))
        self.btn_fan.setText(_translate("Form", "打开风扇"))
