# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 300)
        self.show_btn = QtWidgets.QPushButton(Form)
        self.show_btn.setGeometry(QtCore.QRect(40, 120, 100, 30))
        self.show_btn.setObjectName("show_btn")
        self.show_txt = QtWidgets.QTextBrowser(Form)
        self.show_txt.setGeometry(QtCore.QRect(190, 50, 200, 200))
        self.show_txt.setObjectName("show_txt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.show_btn.setText(_translate("Form", "故宫介绍"))
